/score/create/boxMesh boxMesh_1
/score/mesh/boxSize 20. 0.5 50. cm
/score/mesh/nBin 40 1 100
/score/mesh/translate/xyz 0 0 40 cm
/score/quantity/flatSurfaceCurrent npart
/score/filter/neutral neutron
/score/quantity/flatSurfaceCurrent pipart
/score/filter/neutral pi-
/score/quantity/cellFlux flux0
/score/filter/particleWithKineticEnergy f0 1000 4000 MeV neutron
/score/close

/score/create/cylinderMesh cylMesh_1
/score/mesh/cylinderSize 5 50 cm
/score/mesh/nBin 50 1 1
/score/mesh/translate/xyz 0 0 40 cm
/score/quantity/energyDeposit eDep
/score/close

/score/list


/gun/particle ion
/gun/ion 79 198 79
/run/beamOn 10


/vis/open OGL
/vis/drawVolume worlds
/vis/viewer/set/background white
/vis/viewer/copyViewFrom viewer-0
/vis/scene/add/axes
/score/colorMap/setMinMax ! 0. 20000.
/score/drawProjection boxMesh_1 npart
/score/drawProjection cylMesh_1 eDep
/control/loop drawSlice.mac iColumn 0 49 1
/control/alias iAxis 0
/control/loop drawCylinderSlice.mac iColumn 0 9 1
/score/dumpQuantityToFile cylMesh_1 eDep eDep.txt




