/score/quantity/cellFlux PionFlux0
/score/filter/particleWithKineticEnergy pf0 0 25 MeV pi-
/score/quantity/cellFlux PionFlux1
/score/filter/particleWithKineticEnergy pf1 25 50 MeV pi-
/score/quantity/cellFlux PionFlux2
/score/filter/particleWithKineticEnergy pf2 50 75 MeV pi-
/score/quantity/cellFlux PionFlux3
/score/filter/particleWithKineticEnergy pf3 75 100 MeV pi-
/score/quantity/cellFlux PionFlux4
/score/filter/particleWithKineticEnergy pf4 100 125 MeV pi-
/score/quantity/cellFlux PionFlux5
/score/filter/particleWithKineticEnergy pf5 125 150 MeV pi-
/score/quantity/cellFlux PionFlux6
/score/filter/particleWithKineticEnergy pf6 150 175 MeV pi-
/score/quantity/cellFlux PionFlux7
/score/filter/particleWithKineticEnergy pf7 175 200 MeV pi-
/score/quantity/cellFlux PionFlux8
/score/filter/particleWithKineticEnergy pf8 200 225 MeV pi-
/score/quantity/cellFlux PionFlux9
/score/filter/particleWithKineticEnergy pf9 225 250 MeV pi-
/score/quantity/cellFlux PionFlux10
/score/filter/particleWithKineticEnergy pf10 250 275 MeV pi-
/score/quantity/cellFlux PionFlux11
/score/filter/particleWithKineticEnergy pf11 275 300 MeV pi-
/score/quantity/cellFlux PionFlux12
/score/filter/particleWithKineticEnergy pf12 300 325 MeV pi-
/score/quantity/cellFlux PionFlux13
/score/filter/particleWithKineticEnergy pf13 325 350 MeV pi-
/score/quantity/cellFlux PionFlux14
/score/filter/particleWithKineticEnergy pf14 350 375 MeV pi-
/score/quantity/cellFlux PionFlux15
/score/filter/particleWithKineticEnergy pf15 375 400 MeV pi-
/score/quantity/cellFlux PionFlux16
/score/filter/particleWithKineticEnergy pf16 400 425 MeV pi-
/score/quantity/cellFlux PionFlux17
/score/filter/particleWithKineticEnergy pf17 425 450 MeV pi-
/score/quantity/cellFlux PionFlux18
/score/filter/particleWithKineticEnergy pf18 450 475 MeV pi-
/score/quantity/cellFlux PionFlux19
/score/filter/particleWithKineticEnergy pf19 475 500 MeV pi-
/score/quantity/cellFlux PionFlux20
/score/filter/particleWithKineticEnergy pf20 500 525 MeV pi-
/score/quantity/cellFlux PionFlux21
/score/filter/particleWithKineticEnergy pf21 525 550 MeV pi-
/score/quantity/cellFlux PionFlux22
/score/filter/particleWithKineticEnergy pf22 550 575 MeV pi-
/score/quantity/cellFlux PionFlux23
/score/filter/particleWithKineticEnergy pf23 575 600 MeV pi-
/score/quantity/cellFlux PionFlux24
/score/filter/particleWithKineticEnergy pf24 600 625 MeV pi-
/score/quantity/cellFlux PionFlux25
/score/filter/particleWithKineticEnergy pf25 625 650 MeV pi-
/score/quantity/cellFlux PionFlux26
/score/filter/particleWithKineticEnergy pf26 650 675 MeV pi-
/score/quantity/cellFlux PionFlux27
/score/filter/particleWithKineticEnergy pf27 675 700 MeV pi-
/score/quantity/cellFlux PionFlux28
/score/filter/particleWithKineticEnergy pf28 700 725 MeV pi-
/score/quantity/cellFlux PionFlux29
/score/filter/particleWithKineticEnergy pf29 725 750 MeV pi-
/score/quantity/cellFlux PionFlux30
/score/filter/particleWithKineticEnergy pf30 750 775 MeV pi-
/score/quantity/cellFlux PionFlux31
/score/filter/particleWithKineticEnergy pf31 775 800 MeV pi-
/score/quantity/cellFlux PionFlux32
/score/filter/particleWithKineticEnergy pf32 800 825 MeV pi-
/score/quantity/cellFlux PionFlux33
/score/filter/particleWithKineticEnergy pf33 825 850 MeV pi-
/score/quantity/cellFlux PionFlux34
/score/filter/particleWithKineticEnergy pf34 850 875 MeV pi-
/score/quantity/cellFlux PionFlux35
/score/filter/particleWithKineticEnergy pf35 875 900 MeV pi-
/score/quantity/cellFlux PionFlux36
/score/filter/particleWithKineticEnergy pf36 900 925 MeV pi-
/score/quantity/cellFlux PionFlux37
/score/filter/particleWithKineticEnergy pf37 925 950 MeV pi-
/score/quantity/cellFlux PionFlux38
/score/filter/particleWithKineticEnergy pf38 950 975 MeV pi-
/score/quantity/cellFlux PionFlux39
/score/filter/particleWithKineticEnergy pf39 975 1000 MeV pi-
/score/quantity/cellFlux PionFlux40
/score/filter/particleWithKineticEnergy pf40 1000 1025 MeV pi-
/score/quantity/cellFlux PionFlux41
/score/filter/particleWithKineticEnergy pf41 1025 1050 MeV pi-
/score/quantity/cellFlux PionFlux42
/score/filter/particleWithKineticEnergy pf42 1050 1075 MeV pi-
/score/quantity/cellFlux PionFlux43
/score/filter/particleWithKineticEnergy pf43 1075 1100 MeV pi-
/score/quantity/cellFlux PionFlux44
/score/filter/particleWithKineticEnergy pf44 1100 1125 MeV pi-
/score/quantity/cellFlux PionFlux45
/score/filter/particleWithKineticEnergy pf45 1125 1150 MeV pi-
/score/quantity/cellFlux PionFlux46
/score/filter/particleWithKineticEnergy pf46 1150 1175 MeV pi-
/score/quantity/cellFlux PionFlux47
/score/filter/particleWithKineticEnergy pf47 1175 1200 MeV pi-
/score/quantity/cellFlux PionFlux48
/score/filter/particleWithKineticEnergy pf48 1200 1225 MeV pi-
/score/quantity/cellFlux PionFlux49
/score/filter/particleWithKineticEnergy pf49 1225 1250 MeV pi-
/score/quantity/cellFlux PionFlux50
/score/filter/particleWithKineticEnergy pf50 1250 1275 MeV pi-
/score/quantity/cellFlux PionFlux51
/score/filter/particleWithKineticEnergy pf51 1275 1300 MeV pi-
/score/quantity/cellFlux PionFlux52
/score/filter/particleWithKineticEnergy pf52 1300 1325 MeV pi-
/score/quantity/cellFlux PionFlux53
/score/filter/particleWithKineticEnergy pf53 1325 1350 MeV pi-
/score/quantity/cellFlux PionFlux54
/score/filter/particleWithKineticEnergy pf54 1350 1375 MeV pi-
/score/quantity/cellFlux PionFlux55
/score/filter/particleWithKineticEnergy pf55 1375 1400 MeV pi-
/score/quantity/cellFlux PionFlux56
/score/filter/particleWithKineticEnergy pf56 1400 1425 MeV pi-
/score/quantity/cellFlux PionFlux57
/score/filter/particleWithKineticEnergy pf57 1425 1450 MeV pi-
/score/quantity/cellFlux PionFlux58
/score/filter/particleWithKineticEnergy pf58 1450 1475 MeV pi-
/score/quantity/cellFlux PionFlux59
/score/filter/particleWithKineticEnergy pf59 1475 1500 MeV pi-
/score/quantity/cellFlux PionFlux60
/score/filter/particleWithKineticEnergy pf60 1500 1525 MeV pi-
/score/quantity/cellFlux PionFlux61
/score/filter/particleWithKineticEnergy pf61 1525 1550 MeV pi-
/score/quantity/cellFlux PionFlux62
/score/filter/particleWithKineticEnergy pf62 1550 1575 MeV pi-
/score/quantity/cellFlux PionFlux63
/score/filter/particleWithKineticEnergy pf63 1575 1600 MeV pi-
/score/quantity/cellFlux PionFlux64
/score/filter/particleWithKineticEnergy pf64 1600 1625 MeV pi-
/score/quantity/cellFlux PionFlux65
/score/filter/particleWithKineticEnergy pf65 1625 1650 MeV pi-
/score/quantity/cellFlux PionFlux66
/score/filter/particleWithKineticEnergy pf66 1650 1675 MeV pi-
/score/quantity/cellFlux PionFlux67
/score/filter/particleWithKineticEnergy pf67 1675 1700 MeV pi-
/score/quantity/cellFlux PionFlux68
/score/filter/particleWithKineticEnergy pf68 1700 1725 MeV pi-
/score/quantity/cellFlux PionFlux69
/score/filter/particleWithKineticEnergy pf69 1725 1750 MeV pi-
/score/quantity/cellFlux PionFlux70
/score/filter/particleWithKineticEnergy pf70 1750 1775 MeV pi-
/score/quantity/cellFlux PionFlux71
/score/filter/particleWithKineticEnergy pf71 1775 1800 MeV pi-
/score/quantity/cellFlux PionFlux72
/score/filter/particleWithKineticEnergy pf72 1800 1825 MeV pi-
/score/quantity/cellFlux PionFlux73
/score/filter/particleWithKineticEnergy pf73 1825 1850 MeV pi-
/score/quantity/cellFlux PionFlux74
/score/filter/particleWithKineticEnergy pf74 1850 1875 MeV pi-
/score/quantity/cellFlux PionFlux75
/score/filter/particleWithKineticEnergy pf75 1875 1900 MeV pi-
/score/quantity/cellFlux PionFlux76
/score/filter/particleWithKineticEnergy pf76 1900 1925 MeV pi-
/score/quantity/cellFlux PionFlux77
/score/filter/particleWithKineticEnergy pf77 1925 1950 MeV pi-
/score/quantity/cellFlux PionFlux78
/score/filter/particleWithKineticEnergy pf78 1950 1975 MeV pi-
/score/quantity/cellFlux PionFlux79
/score/filter/particleWithKineticEnergy pf79 1975 2000 MeV pi-
/score/quantity/cellFlux PionFlux80
/score/filter/particleWithKineticEnergy pf80 2000 2025 MeV pi-
/score/quantity/cellFlux PionFlux81
/score/filter/particleWithKineticEnergy pf81 2025 2050 MeV pi-
/score/quantity/cellFlux PionFlux82
/score/filter/particleWithKineticEnergy pf82 2050 2075 MeV pi-
/score/quantity/cellFlux PionFlux83
/score/filter/particleWithKineticEnergy pf83 2075 2100 MeV pi-
/score/quantity/cellFlux PionFlux84
/score/filter/particleWithKineticEnergy pf84 2100 2125 MeV pi-
/score/quantity/cellFlux PionFlux85
/score/filter/particleWithKineticEnergy pf85 2125 2150 MeV pi-
/score/quantity/cellFlux PionFlux86
/score/filter/particleWithKineticEnergy pf86 2150 2175 MeV pi-
/score/quantity/cellFlux PionFlux87
/score/filter/particleWithKineticEnergy pf87 2175 2200 MeV pi-
/score/quantity/cellFlux PionFlux88
/score/filter/particleWithKineticEnergy pf88 2200 2225 MeV pi-
/score/quantity/cellFlux PionFlux89
/score/filter/particleWithKineticEnergy pf89 2225 2250 MeV pi-
/score/quantity/cellFlux PionFlux90
/score/filter/particleWithKineticEnergy pf90 2250 2275 MeV pi-
/score/quantity/cellFlux PionFlux91
/score/filter/particleWithKineticEnergy pf91 2275 2300 MeV pi-
/score/quantity/cellFlux PionFlux92
/score/filter/particleWithKineticEnergy pf92 2300 2325 MeV pi-
/score/quantity/cellFlux PionFlux93
/score/filter/particleWithKineticEnergy pf93 2325 2350 MeV pi-
/score/quantity/cellFlux PionFlux94
/score/filter/particleWithKineticEnergy pf94 2350 2375 MeV pi-
/score/quantity/cellFlux PionFlux95
/score/filter/particleWithKineticEnergy pf95 2375 2400 MeV pi-
/score/quantity/cellFlux PionFlux96
/score/filter/particleWithKineticEnergy pf96 2400 2425 MeV pi-
/score/quantity/cellFlux PionFlux97
/score/filter/particleWithKineticEnergy pf97 2425 2450 MeV pi-
/score/quantity/cellFlux PionFlux98
/score/filter/particleWithKineticEnergy pf98 2450 2475 MeV pi-
/score/quantity/cellFlux PionFlux99
/score/filter/particleWithKineticEnergy pf99 2475 2500 MeV pi-
/score/quantity/cellFlux PionFlux100
/score/filter/particleWithKineticEnergy pf100 2500 2525 MeV pi-
/score/quantity/cellFlux PionFlux101
/score/filter/particleWithKineticEnergy pf101 2525 2550 MeV pi-
/score/quantity/cellFlux PionFlux102
/score/filter/particleWithKineticEnergy pf102 2550 2575 MeV pi-
/score/quantity/cellFlux PionFlux103
/score/filter/particleWithKineticEnergy pf103 2575 2600 MeV pi-
/score/quantity/cellFlux PionFlux104
/score/filter/particleWithKineticEnergy pf104 2600 2625 MeV pi-
/score/quantity/cellFlux PionFlux105
/score/filter/particleWithKineticEnergy pf105 2625 2650 MeV pi-
/score/quantity/cellFlux PionFlux106
/score/filter/particleWithKineticEnergy pf106 2650 2675 MeV pi-
/score/quantity/cellFlux PionFlux107
/score/filter/particleWithKineticEnergy pf107 2675 2700 MeV pi-
/score/quantity/cellFlux PionFlux108
/score/filter/particleWithKineticEnergy pf108 2700 2725 MeV pi-
/score/quantity/cellFlux PionFlux109
/score/filter/particleWithKineticEnergy pf109 2725 2750 MeV pi-
/score/quantity/cellFlux PionFlux110
/score/filter/particleWithKineticEnergy pf110 2750 2775 MeV pi-
/score/quantity/cellFlux PionFlux111
/score/filter/particleWithKineticEnergy pf111 2775 2800 MeV pi-
/score/quantity/cellFlux PionFlux112
/score/filter/particleWithKineticEnergy pf112 2800 2825 MeV pi-
/score/quantity/cellFlux PionFlux113
/score/filter/particleWithKineticEnergy pf113 2825 2850 MeV pi-
/score/quantity/cellFlux PionFlux114
/score/filter/particleWithKineticEnergy pf114 2850 2875 MeV pi-
/score/quantity/cellFlux PionFlux115
/score/filter/particleWithKineticEnergy pf115 2875 2900 MeV pi-
/score/quantity/cellFlux PionFlux116
/score/filter/particleWithKineticEnergy pf116 2900 2925 MeV pi-
/score/quantity/cellFlux PionFlux117
/score/filter/particleWithKineticEnergy pf117 2925 2950 MeV pi-
/score/quantity/cellFlux PionFlux118
/score/filter/particleWithKineticEnergy pf118 2950 2975 MeV pi-
/score/quantity/cellFlux PionFlux119
/score/filter/particleWithKineticEnergy pf119 2975 3000 MeV pi-
/score/quantity/cellFlux PionFlux120
/score/filter/particleWithKineticEnergy pf120 3000 3025 MeV pi-
/score/quantity/cellFlux PionFlux121
/score/filter/particleWithKineticEnergy pf121 3025 3050 MeV pi-
/score/quantity/cellFlux PionFlux122
/score/filter/particleWithKineticEnergy pf122 3050 3075 MeV pi-
/score/quantity/cellFlux PionFlux123
/score/filter/particleWithKineticEnergy pf123 3075 3100 MeV pi-
/score/quantity/cellFlux PionFlux124
/score/filter/particleWithKineticEnergy pf124 3100 3125 MeV pi-
/score/quantity/cellFlux PionFlux125
/score/filter/particleWithKineticEnergy pf125 3125 3150 MeV pi-
/score/quantity/cellFlux PionFlux126
/score/filter/particleWithKineticEnergy pf126 3150 3175 MeV pi-
/score/quantity/cellFlux PionFlux127
/score/filter/particleWithKineticEnergy pf127 3175 3200 MeV pi-
/score/quantity/cellFlux PionFlux128
/score/filter/particleWithKineticEnergy pf128 3200 3225 MeV pi-
/score/quantity/cellFlux PionFlux129
/score/filter/particleWithKineticEnergy pf129 3225 3250 MeV pi-
/score/quantity/cellFlux PionFlux130
/score/filter/particleWithKineticEnergy pf130 3250 3275 MeV pi-
/score/quantity/cellFlux PionFlux131
/score/filter/particleWithKineticEnergy pf131 3275 3300 MeV pi-
/score/quantity/cellFlux PionFlux132
/score/filter/particleWithKineticEnergy pf132 3300 3325 MeV pi-
/score/quantity/cellFlux PionFlux133
/score/filter/particleWithKineticEnergy pf133 3325 3350 MeV pi-
/score/quantity/cellFlux PionFlux134
/score/filter/particleWithKineticEnergy pf134 3350 3375 MeV pi-
/score/quantity/cellFlux PionFlux135
/score/filter/particleWithKineticEnergy pf135 3375 3400 MeV pi-
/score/quantity/cellFlux PionFlux136
/score/filter/particleWithKineticEnergy pf136 3400 3425 MeV pi-
/score/quantity/cellFlux PionFlux137
/score/filter/particleWithKineticEnergy pf137 3425 3450 MeV pi-
/score/quantity/cellFlux PionFlux138
/score/filter/particleWithKineticEnergy pf138 3450 3475 MeV pi-
/score/quantity/cellFlux PionFlux139
/score/filter/particleWithKineticEnergy pf139 3475 3500 MeV pi-
/score/quantity/cellFlux PionFlux140
/score/filter/particleWithKineticEnergy pf140 3500 3525 MeV pi-
/score/quantity/cellFlux PionFlux141
/score/filter/particleWithKineticEnergy pf141 3525 3550 MeV pi-
/score/quantity/cellFlux PionFlux142
/score/filter/particleWithKineticEnergy pf142 3550 3575 MeV pi-
/score/quantity/cellFlux PionFlux143
/score/filter/particleWithKineticEnergy pf143 3575 3600 MeV pi-
/score/quantity/cellFlux PionFlux144
/score/filter/particleWithKineticEnergy pf144 3600 3625 MeV pi-
/score/quantity/cellFlux PionFlux145
/score/filter/particleWithKineticEnergy pf145 3625 3650 MeV pi-
/score/quantity/cellFlux PionFlux146
/score/filter/particleWithKineticEnergy pf146 3650 3675 MeV pi-
/score/quantity/cellFlux PionFlux147
/score/filter/particleWithKineticEnergy pf147 3675 3700 MeV pi-
/score/quantity/cellFlux PionFlux148
/score/filter/particleWithKineticEnergy pf148 3700 3725 MeV pi-
/score/quantity/cellFlux PionFlux149
/score/filter/particleWithKineticEnergy pf149 3725 3750 MeV pi-
/score/quantity/cellFlux PionFlux150
/score/filter/particleWithKineticEnergy pf150 3750 3775 MeV pi-
/score/quantity/cellFlux PionFlux151
/score/filter/particleWithKineticEnergy pf151 3775 3800 MeV pi-
/score/quantity/cellFlux PionFlux152
/score/filter/particleWithKineticEnergy pf152 3800 3825 MeV pi-
/score/quantity/cellFlux PionFlux153
/score/filter/particleWithKineticEnergy pf153 3825 3850 MeV pi-
/score/quantity/cellFlux PionFlux154
/score/filter/particleWithKineticEnergy pf154 3850 3875 MeV pi-
/score/quantity/cellFlux PionFlux155
/score/filter/particleWithKineticEnergy pf155 3875 3900 MeV pi-
/score/quantity/cellFlux PionFlux156
/score/filter/particleWithKineticEnergy pf156 3900 3925 MeV pi-
/score/quantity/cellFlux PionFlux157
/score/filter/particleWithKineticEnergy pf157 3925 3950 MeV pi-
/score/quantity/cellFlux PionFlux158
/score/filter/particleWithKineticEnergy pf158 3950 3975 MeV pi-
/score/quantity/cellFlux PionFlux159
/score/filter/particleWithKineticEnergy pf159 3975 4000 MeV pi-