/score/quantity/cellFlux PionPFlux0
/score/filter/particleWithKineticEnergy ppf0 0 25 MeV pi+
/score/quantity/cellFlux PionPFlux1
/score/filter/particleWithKineticEnergy ppf1 25 50 MeV pi+
/score/quantity/cellFlux PionPFlux2
/score/filter/particleWithKineticEnergy ppf2 50 75 MeV pi+
/score/quantity/cellFlux PionPFlux3
/score/filter/particleWithKineticEnergy ppf3 75 100 MeV pi+
/score/quantity/cellFlux PionPFlux4
/score/filter/particleWithKineticEnergy ppf4 100 125 MeV pi+
/score/quantity/cellFlux PionPFlux5
/score/filter/particleWithKineticEnergy ppf5 125 150 MeV pi+
/score/quantity/cellFlux PionPFlux6
/score/filter/particleWithKineticEnergy ppf6 150 175 MeV pi+
/score/quantity/cellFlux PionPFlux7
/score/filter/particleWithKineticEnergy ppf7 175 200 MeV pi+
/score/quantity/cellFlux PionPFlux8
/score/filter/particleWithKineticEnergy ppf8 200 225 MeV pi+
/score/quantity/cellFlux PionPFlux9
/score/filter/particleWithKineticEnergy ppf9 225 250 MeV pi+
/score/quantity/cellFlux PionPFlux10
/score/filter/particleWithKineticEnergy ppf10 250 275 MeV pi+
/score/quantity/cellFlux PionPFlux11
/score/filter/particleWithKineticEnergy ppf11 275 300 MeV pi+
/score/quantity/cellFlux PionPFlux12
/score/filter/particleWithKineticEnergy ppf12 300 325 MeV pi+
/score/quantity/cellFlux PionPFlux13
/score/filter/particleWithKineticEnergy ppf13 325 350 MeV pi+
/score/quantity/cellFlux PionPFlux14
/score/filter/particleWithKineticEnergy ppf14 350 375 MeV pi+
/score/quantity/cellFlux PionPFlux15
/score/filter/particleWithKineticEnergy ppf15 375 400 MeV pi+
/score/quantity/cellFlux PionPFlux16
/score/filter/particleWithKineticEnergy ppf16 400 425 MeV pi+
/score/quantity/cellFlux PionPFlux17
/score/filter/particleWithKineticEnergy ppf17 425 450 MeV pi+
/score/quantity/cellFlux PionPFlux18
/score/filter/particleWithKineticEnergy ppf18 450 475 MeV pi+
/score/quantity/cellFlux PionPFlux19
/score/filter/particleWithKineticEnergy ppf19 475 500 MeV pi+
/score/quantity/cellFlux PionPFlux20
/score/filter/particleWithKineticEnergy ppf20 500 525 MeV pi+
/score/quantity/cellFlux PionPFlux21
/score/filter/particleWithKineticEnergy ppf21 525 550 MeV pi+
/score/quantity/cellFlux PionPFlux22
/score/filter/particleWithKineticEnergy ppf22 550 575 MeV pi+
/score/quantity/cellFlux PionPFlux23
/score/filter/particleWithKineticEnergy ppf23 575 600 MeV pi+
/score/quantity/cellFlux PionPFlux24
/score/filter/particleWithKineticEnergy ppf24 600 625 MeV pi+
/score/quantity/cellFlux PionPFlux25
/score/filter/particleWithKineticEnergy ppf25 625 650 MeV pi+
/score/quantity/cellFlux PionPFlux26
/score/filter/particleWithKineticEnergy ppf26 650 675 MeV pi+
/score/quantity/cellFlux PionPFlux27
/score/filter/particleWithKineticEnergy ppf27 675 700 MeV pi+
/score/quantity/cellFlux PionPFlux28
/score/filter/particleWithKineticEnergy ppf28 700 725 MeV pi+
/score/quantity/cellFlux PionPFlux29
/score/filter/particleWithKineticEnergy ppf29 725 750 MeV pi+
/score/quantity/cellFlux PionPFlux30
/score/filter/particleWithKineticEnergy ppf30 750 775 MeV pi+
/score/quantity/cellFlux PionPFlux31
/score/filter/particleWithKineticEnergy ppf31 775 800 MeV pi+
/score/quantity/cellFlux PionPFlux32
/score/filter/particleWithKineticEnergy ppf32 800 825 MeV pi+
/score/quantity/cellFlux PionPFlux33
/score/filter/particleWithKineticEnergy ppf33 825 850 MeV pi+
/score/quantity/cellFlux PionPFlux34
/score/filter/particleWithKineticEnergy ppf34 850 875 MeV pi+
/score/quantity/cellFlux PionPFlux35
/score/filter/particleWithKineticEnergy ppf35 875 900 MeV pi+
/score/quantity/cellFlux PionPFlux36
/score/filter/particleWithKineticEnergy ppf36 900 925 MeV pi+
/score/quantity/cellFlux PionPFlux37
/score/filter/particleWithKineticEnergy ppf37 925 950 MeV pi+
/score/quantity/cellFlux PionPFlux38
/score/filter/particleWithKineticEnergy ppf38 950 975 MeV pi+
/score/quantity/cellFlux PionPFlux39
/score/filter/particleWithKineticEnergy ppf39 975 1000 MeV pi+
/score/quantity/cellFlux PionPFlux40
/score/filter/particleWithKineticEnergy ppf40 1000 1025 MeV pi+
/score/quantity/cellFlux PionPFlux41
/score/filter/particleWithKineticEnergy ppf41 1025 1050 MeV pi+
/score/quantity/cellFlux PionPFlux42
/score/filter/particleWithKineticEnergy ppf42 1050 1075 MeV pi+
/score/quantity/cellFlux PionPFlux43
/score/filter/particleWithKineticEnergy ppf43 1075 1100 MeV pi+
/score/quantity/cellFlux PionPFlux44
/score/filter/particleWithKineticEnergy ppf44 1100 1125 MeV pi+
/score/quantity/cellFlux PionPFlux45
/score/filter/particleWithKineticEnergy ppf45 1125 1150 MeV pi+
/score/quantity/cellFlux PionPFlux46
/score/filter/particleWithKineticEnergy ppf46 1150 1175 MeV pi+
/score/quantity/cellFlux PionPFlux47
/score/filter/particleWithKineticEnergy ppf47 1175 1200 MeV pi+
/score/quantity/cellFlux PionPFlux48
/score/filter/particleWithKineticEnergy ppf48 1200 1225 MeV pi+
/score/quantity/cellFlux PionPFlux49
/score/filter/particleWithKineticEnergy ppf49 1225 1250 MeV pi+
/score/quantity/cellFlux PionPFlux50
/score/filter/particleWithKineticEnergy ppf50 1250 1275 MeV pi+
/score/quantity/cellFlux PionPFlux51
/score/filter/particleWithKineticEnergy ppf51 1275 1300 MeV pi+
/score/quantity/cellFlux PionPFlux52
/score/filter/particleWithKineticEnergy ppf52 1300 1325 MeV pi+
/score/quantity/cellFlux PionPFlux53
/score/filter/particleWithKineticEnergy ppf53 1325 1350 MeV pi+
/score/quantity/cellFlux PionPFlux54
/score/filter/particleWithKineticEnergy ppf54 1350 1375 MeV pi+
/score/quantity/cellFlux PionPFlux55
/score/filter/particleWithKineticEnergy ppf55 1375 1400 MeV pi+
/score/quantity/cellFlux PionPFlux56
/score/filter/particleWithKineticEnergy ppf56 1400 1425 MeV pi+
/score/quantity/cellFlux PionPFlux57
/score/filter/particleWithKineticEnergy ppf57 1425 1450 MeV pi+
/score/quantity/cellFlux PionPFlux58
/score/filter/particleWithKineticEnergy ppf58 1450 1475 MeV pi+
/score/quantity/cellFlux PionPFlux59
/score/filter/particleWithKineticEnergy ppf59 1475 1500 MeV pi+
/score/quantity/cellFlux PionPFlux60
/score/filter/particleWithKineticEnergy ppf60 1500 1525 MeV pi+
/score/quantity/cellFlux PionPFlux61
/score/filter/particleWithKineticEnergy ppf61 1525 1550 MeV pi+
/score/quantity/cellFlux PionPFlux62
/score/filter/particleWithKineticEnergy ppf62 1550 1575 MeV pi+
/score/quantity/cellFlux PionPFlux63
/score/filter/particleWithKineticEnergy ppf63 1575 1600 MeV pi+
/score/quantity/cellFlux PionPFlux64
/score/filter/particleWithKineticEnergy ppf64 1600 1625 MeV pi+
/score/quantity/cellFlux PionPFlux65
/score/filter/particleWithKineticEnergy ppf65 1625 1650 MeV pi+
/score/quantity/cellFlux PionPFlux66
/score/filter/particleWithKineticEnergy ppf66 1650 1675 MeV pi+
/score/quantity/cellFlux PionPFlux67
/score/filter/particleWithKineticEnergy ppf67 1675 1700 MeV pi+
/score/quantity/cellFlux PionPFlux68
/score/filter/particleWithKineticEnergy ppf68 1700 1725 MeV pi+
/score/quantity/cellFlux PionPFlux69
/score/filter/particleWithKineticEnergy ppf69 1725 1750 MeV pi+
/score/quantity/cellFlux PionPFlux70
/score/filter/particleWithKineticEnergy ppf70 1750 1775 MeV pi+
/score/quantity/cellFlux PionPFlux71
/score/filter/particleWithKineticEnergy ppf71 1775 1800 MeV pi+
/score/quantity/cellFlux PionPFlux72
/score/filter/particleWithKineticEnergy ppf72 1800 1825 MeV pi+
/score/quantity/cellFlux PionPFlux73
/score/filter/particleWithKineticEnergy ppf73 1825 1850 MeV pi+
/score/quantity/cellFlux PionPFlux74
/score/filter/particleWithKineticEnergy ppf74 1850 1875 MeV pi+
/score/quantity/cellFlux PionPFlux75
/score/filter/particleWithKineticEnergy ppf75 1875 1900 MeV pi+
/score/quantity/cellFlux PionPFlux76
/score/filter/particleWithKineticEnergy ppf76 1900 1925 MeV pi+
/score/quantity/cellFlux PionPFlux77
/score/filter/particleWithKineticEnergy ppf77 1925 1950 MeV pi+
/score/quantity/cellFlux PionPFlux78
/score/filter/particleWithKineticEnergy ppf78 1950 1975 MeV pi+
/score/quantity/cellFlux PionPFlux79
/score/filter/particleWithKineticEnergy ppf79 1975 2000 MeV pi+
/score/quantity/cellFlux PionPFlux80
/score/filter/particleWithKineticEnergy ppf80 2000 2025 MeV pi+
/score/quantity/cellFlux PionPFlux81
/score/filter/particleWithKineticEnergy ppf81 2025 2050 MeV pi+
/score/quantity/cellFlux PionPFlux82
/score/filter/particleWithKineticEnergy ppf82 2050 2075 MeV pi+
/score/quantity/cellFlux PionPFlux83
/score/filter/particleWithKineticEnergy ppf83 2075 2100 MeV pi+
/score/quantity/cellFlux PionPFlux84
/score/filter/particleWithKineticEnergy ppf84 2100 2125 MeV pi+
/score/quantity/cellFlux PionPFlux85
/score/filter/particleWithKineticEnergy ppf85 2125 2150 MeV pi+
/score/quantity/cellFlux PionPFlux86
/score/filter/particleWithKineticEnergy ppf86 2150 2175 MeV pi+
/score/quantity/cellFlux PionPFlux87
/score/filter/particleWithKineticEnergy ppf87 2175 2200 MeV pi+
/score/quantity/cellFlux PionPFlux88
/score/filter/particleWithKineticEnergy ppf88 2200 2225 MeV pi+
/score/quantity/cellFlux PionPFlux89
/score/filter/particleWithKineticEnergy ppf89 2225 2250 MeV pi+
/score/quantity/cellFlux PionPFlux90
/score/filter/particleWithKineticEnergy ppf90 2250 2275 MeV pi+
/score/quantity/cellFlux PionPFlux91
/score/filter/particleWithKineticEnergy ppf91 2275 2300 MeV pi+
/score/quantity/cellFlux PionPFlux92
/score/filter/particleWithKineticEnergy ppf92 2300 2325 MeV pi+
/score/quantity/cellFlux PionPFlux93
/score/filter/particleWithKineticEnergy ppf93 2325 2350 MeV pi+
/score/quantity/cellFlux PionPFlux94
/score/filter/particleWithKineticEnergy ppf94 2350 2375 MeV pi+
/score/quantity/cellFlux PionPFlux95
/score/filter/particleWithKineticEnergy ppf95 2375 2400 MeV pi+
/score/quantity/cellFlux PionPFlux96
/score/filter/particleWithKineticEnergy ppf96 2400 2425 MeV pi+
/score/quantity/cellFlux PionPFlux97
/score/filter/particleWithKineticEnergy ppf97 2425 2450 MeV pi+
/score/quantity/cellFlux PionPFlux98
/score/filter/particleWithKineticEnergy ppf98 2450 2475 MeV pi+
/score/quantity/cellFlux PionPFlux99
/score/filter/particleWithKineticEnergy ppf99 2475 2500 MeV pi+
/score/quantity/cellFlux PionPFlux100
/score/filter/particleWithKineticEnergy ppf100 2500 2525 MeV pi+
/score/quantity/cellFlux PionPFlux101
/score/filter/particleWithKineticEnergy ppf101 2525 2550 MeV pi+
/score/quantity/cellFlux PionPFlux102
/score/filter/particleWithKineticEnergy ppf102 2550 2575 MeV pi+
/score/quantity/cellFlux PionPFlux103
/score/filter/particleWithKineticEnergy ppf103 2575 2600 MeV pi+
/score/quantity/cellFlux PionPFlux104
/score/filter/particleWithKineticEnergy ppf104 2600 2625 MeV pi+
/score/quantity/cellFlux PionPFlux105
/score/filter/particleWithKineticEnergy ppf105 2625 2650 MeV pi+
/score/quantity/cellFlux PionPFlux106
/score/filter/particleWithKineticEnergy ppf106 2650 2675 MeV pi+
/score/quantity/cellFlux PionPFlux107
/score/filter/particleWithKineticEnergy ppf107 2675 2700 MeV pi+
/score/quantity/cellFlux PionPFlux108
/score/filter/particleWithKineticEnergy ppf108 2700 2725 MeV pi+
/score/quantity/cellFlux PionPFlux109
/score/filter/particleWithKineticEnergy ppf109 2725 2750 MeV pi+
/score/quantity/cellFlux PionPFlux110
/score/filter/particleWithKineticEnergy ppf110 2750 2775 MeV pi+
/score/quantity/cellFlux PionPFlux111
/score/filter/particleWithKineticEnergy ppf111 2775 2800 MeV pi+
/score/quantity/cellFlux PionPFlux112
/score/filter/particleWithKineticEnergy ppf112 2800 2825 MeV pi+
/score/quantity/cellFlux PionPFlux113
/score/filter/particleWithKineticEnergy ppf113 2825 2850 MeV pi+
/score/quantity/cellFlux PionPFlux114
/score/filter/particleWithKineticEnergy ppf114 2850 2875 MeV pi+
/score/quantity/cellFlux PionPFlux115
/score/filter/particleWithKineticEnergy ppf115 2875 2900 MeV pi+
/score/quantity/cellFlux PionPFlux116
/score/filter/particleWithKineticEnergy ppf116 2900 2925 MeV pi+
/score/quantity/cellFlux PionPFlux117
/score/filter/particleWithKineticEnergy ppf117 2925 2950 MeV pi+
/score/quantity/cellFlux PionPFlux118
/score/filter/particleWithKineticEnergy ppf118 2950 2975 MeV pi+
/score/quantity/cellFlux PionPFlux119
/score/filter/particleWithKineticEnergy ppf119 2975 3000 MeV pi+
/score/quantity/cellFlux PionPFlux120
/score/filter/particleWithKineticEnergy ppf120 3000 3025 MeV pi+
/score/quantity/cellFlux PionPFlux121
/score/filter/particleWithKineticEnergy ppf121 3025 3050 MeV pi+
/score/quantity/cellFlux PionPFlux122
/score/filter/particleWithKineticEnergy ppf122 3050 3075 MeV pi+
/score/quantity/cellFlux PionPFlux123
/score/filter/particleWithKineticEnergy ppf123 3075 3100 MeV pi+
/score/quantity/cellFlux PionPFlux124
/score/filter/particleWithKineticEnergy ppf124 3100 3125 MeV pi+
/score/quantity/cellFlux PionPFlux125
/score/filter/particleWithKineticEnergy ppf125 3125 3150 MeV pi+
/score/quantity/cellFlux PionPFlux126
/score/filter/particleWithKineticEnergy ppf126 3150 3175 MeV pi+
/score/quantity/cellFlux PionPFlux127
/score/filter/particleWithKineticEnergy ppf127 3175 3200 MeV pi+
/score/quantity/cellFlux PionPFlux128
/score/filter/particleWithKineticEnergy ppf128 3200 3225 MeV pi+
/score/quantity/cellFlux PionPFlux129
/score/filter/particleWithKineticEnergy ppf129 3225 3250 MeV pi+
/score/quantity/cellFlux PionPFlux130
/score/filter/particleWithKineticEnergy ppf130 3250 3275 MeV pi+
/score/quantity/cellFlux PionPFlux131
/score/filter/particleWithKineticEnergy ppf131 3275 3300 MeV pi+
/score/quantity/cellFlux PionPFlux132
/score/filter/particleWithKineticEnergy ppf132 3300 3325 MeV pi+
/score/quantity/cellFlux PionPFlux133
/score/filter/particleWithKineticEnergy ppf133 3325 3350 MeV pi+
/score/quantity/cellFlux PionPFlux134
/score/filter/particleWithKineticEnergy ppf134 3350 3375 MeV pi+
/score/quantity/cellFlux PionPFlux135
/score/filter/particleWithKineticEnergy ppf135 3375 3400 MeV pi+
/score/quantity/cellFlux PionPFlux136
/score/filter/particleWithKineticEnergy ppf136 3400 3425 MeV pi+
/score/quantity/cellFlux PionPFlux137
/score/filter/particleWithKineticEnergy ppf137 3425 3450 MeV pi+
/score/quantity/cellFlux PionPFlux138
/score/filter/particleWithKineticEnergy ppf138 3450 3475 MeV pi+
/score/quantity/cellFlux PionPFlux139
/score/filter/particleWithKineticEnergy ppf139 3475 3500 MeV pi+
/score/quantity/cellFlux PionPFlux140
/score/filter/particleWithKineticEnergy ppf140 3500 3525 MeV pi+
/score/quantity/cellFlux PionPFlux141
/score/filter/particleWithKineticEnergy ppf141 3525 3550 MeV pi+
/score/quantity/cellFlux PionPFlux142
/score/filter/particleWithKineticEnergy ppf142 3550 3575 MeV pi+
/score/quantity/cellFlux PionPFlux143
/score/filter/particleWithKineticEnergy ppf143 3575 3600 MeV pi+
/score/quantity/cellFlux PionPFlux144
/score/filter/particleWithKineticEnergy ppf144 3600 3625 MeV pi+
/score/quantity/cellFlux PionPFlux145
/score/filter/particleWithKineticEnergy ppf145 3625 3650 MeV pi+
/score/quantity/cellFlux PionPFlux146
/score/filter/particleWithKineticEnergy ppf146 3650 3675 MeV pi+
/score/quantity/cellFlux PionPFlux147
/score/filter/particleWithKineticEnergy ppf147 3675 3700 MeV pi+
/score/quantity/cellFlux PionPFlux148
/score/filter/particleWithKineticEnergy ppf148 3700 3725 MeV pi+
/score/quantity/cellFlux PionPFlux149
/score/filter/particleWithKineticEnergy ppf149 3725 3750 MeV pi+
/score/quantity/cellFlux PionPFlux150
/score/filter/particleWithKineticEnergy ppf150 3750 3775 MeV pi+
/score/quantity/cellFlux PionPFlux151
/score/filter/particleWithKineticEnergy ppf151 3775 3800 MeV pi+
/score/quantity/cellFlux PionPFlux152
/score/filter/particleWithKineticEnergy ppf152 3800 3825 MeV pi+
/score/quantity/cellFlux PionPFlux153
/score/filter/particleWithKineticEnergy ppf153 3825 3850 MeV pi+
/score/quantity/cellFlux PionPFlux154
/score/filter/particleWithKineticEnergy ppf154 3850 3875 MeV pi+
/score/quantity/cellFlux PionPFlux155
/score/filter/particleWithKineticEnergy ppf155 3875 3900 MeV pi+
/score/quantity/cellFlux PionPFlux156
/score/filter/particleWithKineticEnergy ppf156 3900 3925 MeV pi+
/score/quantity/cellFlux PionPFlux157
/score/filter/particleWithKineticEnergy ppf157 3925 3950 MeV pi+
/score/quantity/cellFlux PionPFlux158
/score/filter/particleWithKineticEnergy ppf158 3950 3975 MeV pi+
/score/quantity/cellFlux PionPFlux159
/score/filter/particleWithKineticEnergy ppf159 3975 4000 MeV pi+